export class CollegesConstants {
  static readonly ITEM_WIDTH: number = 86;
  static readonly SHOW_COUNT: number = 5;
  static readonly HALF_COUNT: number = Math.floor(CollegesConstants.SHOW_COUNT / 2);
  static readonly OPACITY_COEFFICIENTS: number = 0.1;
  static readonly OFFSET_COEFFICIENTS: number = 10;
  static readonly MAX_OFFSET_Y: number = 100;
  static readonly MAX_MOVE_OFFSET: number = 60;
}